package sprint_1;

import java.util.Scanner;

public class Simulator {
	String inputType;
	Boolean inputloop=true;
	Scanner input= new Scanner(System.in);
//	Create a simulator that issues events for the Chronotimer and has a system 
//	clock. Events should be generated by reading in text from the command file or the console.
	public String getinput(){
	while(inputloop){
		System.out.println("Do you want user input or input from a file? U:user input and T:text file");
		inputType=input.nextLine();
		if(inputType.equalsIgnoreCase("U")||inputType.equalsIgnoreCase("T"){
			inputloop=false;
		}
	}
	if(inputType.equalsIgnoreCase("U")){
		System.out.println("Enter a Command");
		System.o
		
	}
	if(inputType.equalsIgnoreCase("T")){
		
	}
	}
	
}
